name: Build eLinux (Gitea)

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-elinux:
    runs-on: kky
    
    strategy:
      matrix:
        target: [x64]
        backend: [wayland, x11]
    
    steps:
      - name: Checkout
        run: |
          git clone --recursive ${{ gitea.server_url }}/${{ gitea.repository }}.git .
          git checkout ${{ gitea.sha }}

      - name: Install dependencies
        run: |
          apt-get update || true
          apt-get install -y clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev libstdc++-12-dev \
            curl git unzip xz-utils zip || true

      - name: Setup Flutter (cached in /opt/flutter-cache)
        run: |
          CACHE_DIR="/opt/flutter-cache"
          mkdir -p $CACHE_DIR
          
          # Cache Flutter SDK - try multiple mirrors
          if [ ! -d "$CACHE_DIR/flutter" ]; then
            echo "Downloading Flutter SDK..."
            git clone https://gitee.com/mirrors/Flutter.git -b 3.24.0 --depth 1 $CACHE_DIR/flutter || \
            git clone https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git -b 3.24.0 --depth 1 $CACHE_DIR/flutter || \
            git clone https://github.com/flutter/flutter.git -b 3.24.0 --depth 1 $CACHE_DIR/flutter
          else
            echo "Using cached Flutter SDK"
          fi
          
          # Cache flutter-elinux
          if [ ! -d "$CACHE_DIR/flutter-elinux" ]; then
            echo "Downloading flutter-elinux..."
            git clone https://gitee.com/panda-mute/flutter-elinux.git --depth 1 $CACHE_DIR/flutter-elinux || \
            git clone https://github.com/sony/flutter-elinux.git --depth 1 $CACHE_DIR/flutter-elinux
          else
            echo "Using cached flutter-elinux"
          fi
          
          # Use China mirror for Flutter artifacts
          export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
          export PUB_HOSTED_URL=https://pub.flutter-io.cn
          
          export PATH="$CACHE_DIR/flutter-elinux/bin:$CACHE_DIR/flutter/bin:$PATH"
          flutter precache --linux
          flutter-elinux doctor

      - name: Build eLinux (${{ matrix.target }} - ${{ matrix.backend }})
        run: |
          CACHE_DIR="/opt/flutter-cache"
          export PATH="$CACHE_DIR/flutter-elinux/bin:$CACHE_DIR/flutter/bin:$PATH"
          export PUB_CACHE="$CACHE_DIR/pub-cache"
          export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
          export PUB_HOSTED_URL=https://pub.flutter-io.cn
          mkdir -p $PUB_CACHE
          
          cd example
          flutter pub get
          flutter-elinux build elinux \
            --target-arch=${{ matrix.target }} \
            --target-backend-type=${{ matrix.backend }} \
            --release

      - name: Package artifact
        run: |
          cd example/build/elinux/${{ matrix.target }}/release
          tar -czvf elinux-${{ matrix.target }}-${{ matrix.backend }}.tar.gz bundle/
          echo "Build completed: elinux-${{ matrix.target }}-${{ matrix.backend }}.tar.gz"
