name: Build eLinux (Gitea)

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-elinux:
    runs-on: kky
    
    strategy:
      matrix:
        target: [x64]
        backend: [wayland, x11]
    
    steps:
      - name: Checkout
        run: |
          git clone --recursive ${{ gitea.server_url }}/${{ gitea.repository }}.git .
          git checkout ${{ gitea.sha }}

      - name: Install dependencies
        run: |
          apt-get update || true
          apt-get install -y clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev libstdc++-12-dev \
            curl git unzip xz-utils zip || true

      - name: Setup Flutter
        run: |
          if [ ! -d "$HOME/flutter" ]; then
            git clone https://ghproxy.com/https://github.com/flutter/flutter.git -b 3.24.0 $HOME/flutter
          fi
          export PATH="$HOME/flutter/bin:$PATH"
          flutter doctor -v

      - name: Setup flutter-elinux
        run: |
          if [ ! -d "$HOME/flutter-elinux" ]; then
            git clone https://ghproxy.com/https://github.com/sony/flutter-elinux.git $HOME/flutter-elinux
          fi
          export PATH="$HOME/flutter-elinux/bin:$HOME/flutter/bin:$PATH"
          flutter-elinux doctor

      - name: Build eLinux (${{ matrix.target }} - ${{ matrix.backend }})
        run: |
          export PATH="$HOME/flutter-elinux/bin:$HOME/flutter/bin:$PATH"
          cd example
          flutter pub get
          flutter-elinux build elinux \
            --target-arch=${{ matrix.target }} \
            --target-backend-type=${{ matrix.backend }} \
            --release

      - name: Package artifact
        run: |
          cd example/build/elinux/${{ matrix.target }}/release
          tar -czvf elinux-${{ matrix.target }}-${{ matrix.backend }}.tar.gz bundle/
          echo "Build completed: elinux-${{ matrix.target }}-${{ matrix.backend }}.tar.gz"
